### ISSUE TITLE
Just use styles.less

### ISSUE THREAD

**Issue by mrodalgaard** [richarddewit/n1-custom-stylesheet#1]
Instead of creating a full plugin for this, just add a `styles.less` file in your Nylas directory (`~/.nylas/styles.less` on unix systems). It is picked up by Nylas N1 on startup and applied to the DOM. It is documented further by Atom [HERE](https://atom.io/docs/latest/using-atom-basic-customization#style-tweaks).

**Comment by richarddewit** [comment]
Oh wow, I didn't know that as it doesn't exist by default. Thanks!
*DELETING REPO IN 3... 2... 1...*
